name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js project
        run: yarn build

      - name: Archive production build
        run: |
          mkdir -p deployment
          cp -r .next public package.json yarn.lock deployment/
          tar -czf deployment.tar.gz -C deployment .

      - name: Upload production build to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./deployment.tar.gz"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Clean up
        run: rm deployment.tar.gz
